### ISSUE TITLE
在maven中搜不到此包

### ISSUE THREAD

**Issue by muxiaobai** [QcloudApi/qcloudapi-sdk-java#10]
![q](https://cloud.githubusercontent.com/assets/13265901/16712391/7266973a-46b8-11e6-9d97-8f390a224b81.PNG)

**Comment by QiangFu310** [comment]
同问，能否把java sdk放到maven上去？

**Comment by zhhyang** [comment]
可以把源码down下来，放到自己的私服里去

**Comment by fmpoffice** [comment]
别用maven不行麽？都已经直接有源码的啊！！！ @JasonFuBooking @muxiaobai

**Comment by QiangFu310** [comment]
知道啦谢谢楼上各位
...我只是问一问嘛...因为我们用CI的工具来编译和部署项目，如果放在maven上可以方便的自动部署。我自己下源码的话还要自己搭一个maven的endpoint（@zidaneaa）。如果是自己硬拷贝进项目....
总之就是我懒行了吧

**Comment by fengcs** [comment]
支持楼主，API就是要方便好用，公认最方便的方式当然是maven库。

**Comment by QcloudApi** [comment]
maven依赖：

    <dependency>
    <groupId>com.qcloud</groupId>
    <artifactId>qcloud-java-sdk</artifactId>
    <version>2.0.1</version>
    </dependency>
