### ISSUE TITLE
错误信息中包含双引号导致json解析失败

### ISSUE THREAD

**Issue by candowu** [QcloudApi/qcloudapi-sdk-java#11]
{"code":-2700,"location":"com.qcloud.Common.Request:225","message":"api sdk throw exception! java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden""}

com.qcloud.Utilities.Json.JSONException: Expected a ',' or '}' at 162 [character 163 line 1]

**Comment by QcloudApi** [comment]
这是由于未能将底层抛出的字符串中的特殊符号进行转义造成的。
我们已经在cf8d055a347ba49d1cfa051d911a0e805f4ee76f中将其修复，并计划包含在2.0.5版本中发布。
很抱歉未能及时回应您的问题。
