### ISSUE TITLE
建议增加对proxy的支持

### ISSUE THREAD

**Issue by candowu** [QcloudApi/qcloudapi-sdk-java#12]
使用api的服务器没有外网权限，需要通过proxy访问外网，建议增加对proxy的支持。

**Comment by QcloudApi** [comment]
您可以使用全局代理，例如运行demo示例代码时可以如下运行

    javac Demo.java
    java -DproxySet=true -Dhttps.proxyHost=实际代理域名 -Dhttps.proxyPort=实际代理端口 Demo

注意，Demo.java中需要填写您真实的secretId和secretKey。

或者在您的代码中设置全局代理，例如

        System.setProperty("http.proxySet", "true"); 
        System.setProperty("http.proxyHost", "实际代理域名"); 
        System.setProperty("http.proxyPort", "实际代理端口");
        System.setProperty("https.proxyHost", "实际代理域名"); 
        System.setProperty("https.proxyPort", "实际代理端口");
