### ISSUE TITLE
建议添加maven支持

### ISSUE THREAD

**Issue by fengcs** [QcloudApi/qcloudapi-sdk-java#13]
直接源码引入的方式不够优美，破坏代码结构。建议添加maven jar包的形式引入！

**Comment by jackyZL** [comment]
真是垃圾，和百度vod的文档不能比~ 关键是maven都不支持。 搞笑了~

**Comment by QcloudApi** [comment]
maven依赖：

    <dependency>
    <groupId>com.qcloud</groupId>
    <artifactId>qcloud-java-sdk</artifactId>
    <version>2.0.1</version>
    </dependency>
