### ISSUE TITLE
文档和百度VOD简直不能比~  还要download源码，maven都不支持，是懒还是不负责呢？

### ISSUE THREAD

**Issue by jackyZL** [QcloudApi/qcloudapi-sdk-java#14]

**Comment by weisong82** [comment]
mvn有，就是按这个artifactId 找不到
<dependency>
<groupId>com.qcloud</groupId>
<artifactId>qcloud-java-sdk</artifactId>
<version>2.0.1</version>
</dependency>

**Comment by QcloudApi** [comment]
maven依赖：

    <dependency>
    <groupId>com.qcloud</groupId>
    <artifactId>qcloud-java-sdk</artifactId>
    <version>2.0.1</version>
    </dependency>
