### ISSUE TITLE
怎么没有域名相关的API？话说域名接口总是返回6100怎么破

### ISSUE THREAD

**Issue by ankanch** [QcloudApi/qcloudapi-sdk-java#17]
完完全全按照API文档来写的，总是6100？那个域名的region怎么选择啊？

**Comment by chb992983141** [comment]
1. 6100应该就是你的地域参数选错了，接口是在对应的地域才能调用成功的。
2. 地域的region就是你希望这个机子是生产在哪个地区。
地域选择tips：
应根据您的用户所在地理位置选择地域。云服务器与访问客户端距离越近，越能获得较小的访问时延和较高的访问速度。比如您的用户大部分位于长江三角洲附近时，上海地域是较好的选择。
请注意，不同地域之间的云服务器不能通过内网互相通信（通信需经过公网，收费），相同地域下的云服务器可以通过内网相互通信（内网通信不收费）。
可选的项有--->gz:广州; sh:上海; hk:香港; ca:北美;

**Comment by luis-wang** [comment]
地域也肯定是对的，直接返回6100错误，提示怎么一点都不明确呢 ？

**Comment by chb992983141** [comment]
那就只能建议你去腾讯云官方QQ群里面问下，里面的回复也是挺快的。
群号：385066281，(๑•̀ㅂ•́)و✧加油，祝好运！！！
