### ISSUE TITLE
文档里说明需要对请求按字典排序

### ISSUE THREAD

**Issue by zvrr** [QcloudApi/qcloudapi-sdk-java#2]
但是在代码里面并没有相应的map按key排序，总是报签名错误？这个是一个bug吗？
(1). 对参数排序
对请求参数按参数名做字典序升序排列（例如php中可使用ksort函数排序） , 结果如下:
http://wiki.qcloud.com/wiki/%E6%8E%A5%E5%8F%A3%E9%89%B4%E6%9D%83

**Comment by lhkzh** [comment]
利用 TreeMap，自动给做了呢
