### ISSUE TITLE
使用TextKeywords方法会出现{"message":"本版本内不支持的接口或者接口已经被废弃，请参考该接口的文档。","code":6100}

### ISSUE THREAD

**Issue by LintBin** [QcloudApi/qcloudapi-sdk-java#4]
我使用sdk调用TextKeywords接口，返回的是{"message":"本版本内不支持的接口或者接口已经被废弃，请参考该接口的文档。","code":6100}。这个版本的sdk不支持TextKeywords接口吗？

**Comment by QcloudApi** [comment]
是您调用的某个接口例如cvm的DescribeInstances接口已经不再支持了（这里拿DescribeInstances举例而已，它还健在，恩）。
