### ISSUE TITLE
Vod 中MultipartUploadVodFile上传，fileName定义有问题

### ISSUE THREAD

**Issue by zhhyang** [QcloudApi/qcloudapi-sdk-java#5]
再demo中 String fileName = "d:\test.rmvb";
这样定义只适合在开发测试阶段，在服务器中是无法直接读取客户端的文件地址全路径的。
如果我修改该SDK，修改的地方实在是太多，修改完又担心以后的SDK的升级问题

**Comment by lordpeas** [comment]
是的，写sdk的人好坑

**Comment by QcloudApi** [comment]
很抱歉给您带来了困扰。

当初写demo的时候的确写的有问题，现在vod的这个MultipartUploadVodFile接口已经废弃不用，我们也无法调试了，只能从SDK中删除掉相关代码。
