### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by 0827moon** [QcloudApi/qcloudapi-sdk-java#6]
运行时遇到
{"code":-2700,"location":"com.qcloud.Common.Request:225","message":"api sdk throw exception! java.net.SocketTimeoutException: connect timed out"}
将Request.java中所有关于timeout的语句都取消掉依然有这个问题，请问是什么原因导致呢？

**Comment by QcloudApi** [comment]
这是因为您网络不通，可能您的防火墙阻止了，或者您是在一个代理的环境下。一般都是由于代理问题造成的。

您可以使用全局代理，例如运行demo示例代码时可以如下运行

    javac Demo.java
    java -DproxySet=true -Dhttps.proxyHost=实际代理域名 -Dhttps.proxyPort=实际代理端口 Demo

注意，Demo.java中需要填写您真实的secretId和secretKey。

或者在您的代码中设置全局代理，例如

    System.setProperty("http.proxySet", "true"); 
    System.setProperty("http.proxyHost", "实际代理域名"); 
    System.setProperty("http.proxyPort", "实际代理端口");
    System.setProperty("https.proxyHost", "实际代理域名"); 
    System.setProperty("https.proxyPort", "实际代理端口");
