### ISSUE TITLE
请求的数据中duration等数字型的为0

### ISSUE THREAD

**Issue by caige2015** [QcloudApi/qcloudapi-sdk-java#7]
在demo中main方法可以返回数据，但封装成工具类在接口中去请求时，所有的类似duration类型的数据都没请求到，返回的是0，什么原因，急求解决！

**Comment by QcloudApi** [comment]
由于没有提及具体是哪个产品的哪个具体接口，我们很难复现定位或者提供帮助。

目前SDK中返回的是json字符串，请考虑是否是转换时发生了错误。

对于我们未能及时回应您的疑问，深感抱歉。这个issue时间太久了，我们暂时将其关闭。如果您看到了我们的回复，能提供信息供我们进一步排查，您可以随时再将其打开。谢谢。
