### ISSUE TITLE
android上传的错误码在哪?

### ISSUE THREAD

**Issue by kaershushu** [QcloudApi/qcloudapi-sdk-java#9]
https://www.qcloud.com/doc/product 这个是错误码界面吗?明显不是,android文档里也没有错误码的相关记录,写个文档走点心行吗

**Comment by lgengsy** [comment]
Q的服务好用么 ？

**Comment by kaershushu** [comment]
还可以，错误码不好找就是了

**Comment by QcloudApi** [comment]
一般接口会给出接口的错误码和公共的错误码，例如云服务器的查看实例列表接口https://cloud.tencent.com/document/product/213/9388 
![image](https://user-images.githubusercontent.com/9277281/34509358-2b1140e8-f084-11e7-9775-f5d337ce5987.png)
如果某个具体产品的API文档不全面得联系该产品的开发人员补齐文档。您可以直接在工单系统中提出意见。谢谢。
